### ISSUE TITLE
Turns start before reloads

### ISSUE THREAD

**Issue by curcio** [google/qpp#90]
After the first reload, we recieve the startTurn message before the reload message. This causes problems to store the first turn in the correct Load object. 

Example:
Open demo.html and start qpp.
Apply lastChange on obj.prop.
Apply lastChange on condition.value 
Console reads:
qp| startTurn 1 undefined ? undefined BeginLoading 
qp| reload 2 ----------------------- Querypoint Runtime Initialized ---------------------------------

The turn is actually stored as if it happened in load 1. This can be seen in the scrubber bar when selecting load 1, the last message is the first turn.

**Comment by curcio** [comment]
I couldn't find a way for the messages to appear in the console correctly, so since the problem was noticeable with the first turn of every load, I manually change the turn's load number if it's the first turn.

But I didn't really want to close the issue because the first start turn message is still being sent before the reload message

**Comment by johnjbarton** [comment]
I committed a fix for this on branch issue90. However at least test http://localhost:8686/test/LayoutTests/Panel/traceElement-expected.txt:
fails because the turns are not matched to the logScrubber elements. Some how the matching mechanism isn't robust enough; we need to come up with a solution that is less likely to get off track.

**Comment by curcio** [comment]
The problem is that I was manually changing the load number for the first turn in Log.js. If I remove that line everything seems to be working properly. There is still an issue with tests, because we have 1 less turn (anWeBegin used to be a turn), so those that had wait for a turn number are giving timeout
